<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CustomerPortalController;
use App\Http\Controllers\UnitGlampingController;
use App\Http\Controllers\FnbMenuController;
use App\Http\Controllers\MasterCustomerController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\TarifController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\CheckInOutController;
use App\Http\Controllers\FnbOrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\HousekeepingController;
use App\Http\Controllers\CrmController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\DssController;
use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;

// Portal Customer (publik)
Route::get('/', [CustomerPortalController::class, 'index'])->name('home');
Route::get('/booking', [CustomerPortalController::class, 'booking'])->name('booking');
Route::post('/booking', [CustomerPortalController::class, 'store'])->name('booking.store');
Route::get('/booking/confirmation/{code}', [CustomerPortalController::class, 'confirmation'])->name('booking.confirmation');

// Auth routes generated by Breeze
require __DIR__.'/auth.php';

// Sistem ERP (butuh login)
Route::middleware(['auth'])->prefix('erp')->name('erp.')->group(function () {

    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Master
    Route::middleware(['role:admin|front_office'])->prefix('master')->name('master.')->group(function () {
        Route::resource('units', UnitGlampingController::class);
        Route::resource('menu', FnbMenuController::class);
        Route::resource('customers', MasterCustomerController::class);
        Route::resource('staff', StaffController::class)->middleware('role:admin');
        Route::resource('tarif', TarifController::class)->middleware('role:admin');
    });

    // Transaksi
    Route::prefix('transaksi')->name('transaksi.')->group(function () {
        // Reservasi
        Route::resource('reservasi', ReservationController::class)->middleware('role:admin|front_office');
        Route::post('reservasi/{reservasi}/confirm', [ReservationController::class, 'confirm'])->name('reservasi.confirm')->middleware('role:admin|front_office');
        Route::post('reservasi/{reservasi}/cancel', [ReservationController::class, 'cancel'])->name('reservasi.cancel')->middleware('role:admin|front_office');

        // Check-in & Check-out
        Route::get('checkin', [CheckInOutController::class, 'checkInForm'])->name('checkin.form')->middleware('role:admin|front_office');
        Route::post('checkin', [CheckInOutController::class, 'processCheckIn'])->name('checkin.process')->middleware('role:admin|front_office');
        Route::get('checkout/{id}', [CheckInOutController::class, 'checkOutForm'])->name('checkout.form')->middleware('role:admin|front_office');
        Route::post('checkout/{id}', [CheckInOutController::class, 'processCheckOut'])->name('checkout.process')->middleware('role:admin|front_office');

        // F&B
        Route::resource('fnb', FnbOrderController::class)->middleware('role:admin|fnb_staff');
        
        // Pembayaran / Billing
        Route::get('pembayaran', [BillingController::class, 'index'])->name('pembayaran.index')->middleware('role:admin|finance');
        Route::get('pembayaran/{id}', [BillingController::class, 'show'])->name('pembayaran.show')->middleware('role:admin|finance');
        
        // Housekeeping
        Route::resource('housekeeping', HousekeepingController::class)->middleware('role:admin|housekeeping');
    });

    // CRM
    Route::middleware(['role:admin'])->prefix('crm')->name('crm.')->group(function () {
        Route::get('/', [CrmController::class, 'index'])->name('index');
        Route::get('/{id}', [CrmController::class, 'show'])->name('show');
        Route::post('/{id}/note', [CrmController::class, 'addNote'])->name('note');
    });

    // Laporan
    Route::middleware(['role:admin|finance'])->prefix('laporan')->name('laporan.')->group(function () {
        Route::get('/reservasi', [LaporanController::class, 'reservasi'])->name('reservasi');
        Route::get('/pendapatan', [LaporanController::class, 'pendapatan'])->name('pendapatan');
        Route::get('/okupansi', [LaporanController::class, 'okupansi'])->name('okupansi');
        Route::get('/fnb', [LaporanController::class, 'fnb'])->name('fnb');
        Route::get('/invoice/{id}/download', [BillingController::class, 'downloadInvoice'])->name('invoice.download');
    });

    // DSS
    Route::middleware(['role:admin'])->prefix('dss')->name('dss.')->group(function () {
        Route::get('/', [DssController::class, 'index'])->name('index');
    });

    // Pengaturan
    Route::middleware(['role:admin'])->prefix('settings')->name('settings.')->group(function () {
        Route::get('/roles', [SettingsController::class, 'roles'])->name('roles');
        Route::get('/profil', [SettingsController::class, 'profil'])->name('profil');
    });
});
